# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquivalenceClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('deprecated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='identifier',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='id_mappings.Scheme'),
        ),
        migrations.AddField(
            model_name='equivalenceclaim',
            name='identifier_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims_via_a', to='id_mappings.Identifier'),
        ),
        migrations.AddField(
            model_name='equivalenceclaim',
            name='identifier_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims_via_b', to='id_mappings.Identifier'),
        ),
    ]
