# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('id_mappings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equivalenceclaim',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
