# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_mappings', '0003_equivalenceclaim_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='equivalenceclaim',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
